In [2]:
#Ans01 : Yes, there is a difference in the data type of variables list_ and array_list.
#list_ is a Python list object that can contain any type of Python objects including strings, integers, floats, etc.
#array_list is a numpy array object that can only contain elements of a single data type. In this case, since all the elements in list_ are strings, array_list will also contain elements of the string data type.

# *You can use the type() function as follows:

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


In [3]:
#Ans02 : 

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# printing data types of elements in list_
for element in list_:
    print("Data type of element {} in list_: {}".format(element, type(element)))

# printing data types of elements in array_list
for element in array_list:
    print("Data type of element {} in array_list: {}".format(element, type(element)))


Data type of element 1 in list_: <class 'str'>
Data type of element 2 in list_: <class 'str'>
Data type of element 3 in list_: <class 'str'>
Data type of element 4 in list_: <class 'str'>
Data type of element 5 in list_: <class 'str'>
Data type of element 1 in array_list: <class 'numpy.str_'>
Data type of element 2 in array_list: <class 'numpy.str_'>
Data type of element 3 in array_list: <class 'numpy.str_'>
Data type of element 4 in array_list: <class 'numpy.str_'>
Data type of element 5 in array_list: <class 'numpy.str_'>


In [5]:
#Ans03 : Yes, there will be a difference in the data type of the elements present in list_ and array_list when array_list is defined as np.array(object=list_, dtype=int).
# In this case, the dtype parameter is set to int, which means that the elements of list_ will be converted to integers when they are assigned to array_list. Therefore, the data type of each element in array_list will be int instead of numpy.str_.

#You can use a loop along with the type() function as follows:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# printing data types of elements in list_
for element in list_:
    print("Data type of element {} in list_: {}".format(element, type(element)))

# printing data types of elements in array_list
for element in array_list:
    print("Data type of element {} in array_list: {}".format(element, type(element)))


Data type of element 1 in list_: <class 'str'>
Data type of element 2 in list_: <class 'str'>
Data type of element 3 in list_: <class 'str'>
Data type of element 4 in list_: <class 'str'>
Data type of element 5 in list_: <class 'str'>
Data type of element 1 in array_list: <class 'numpy.int64'>
Data type of element 2 in array_list: <class 'numpy.int64'>
Data type of element 3 in array_list: <class 'numpy.int64'>
Data type of element 4 in array_list: <class 'numpy.int64'>
Data type of element 5 in array_list: <class 'numpy.int64'>


In [6]:
#Ans04 : 
# To find the shape and size of a numpy array, you can use the shape and size attributes of the numpy array.
# For the variable num_array in the given code, the shape of the array will be (2,3) since it has 2 rows and 3 columns, and the size of the array will be 6 since it contains a total of 6 elements.
# EXAMPLE :

import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# finding shape of num_array
print("Shape of num_array:", num_array.shape)

# finding size of num_array
print("Size of num_array:", num_array.size)


Shape of num_array: (2, 3)
Size of num_array: 6


In [9]:
#Ans05 : To create a numpy array of a 3x3 matrix containing zeros only, you can use the np.zeros() function. This function takes a shape tuple as input and creates an array of the specified shape filled with zeros.
# code to create the desired numpy array:
import numpy as np

# create a numpy array of 3x3 matrix containing zeros only
zero_array = np.zeros(shape=(3, 3))

# print the resulting numpy array
print(zero_array)



[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#Ans06 : 